import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  // Splash Screen Styles
  splashContainer: {
    flex: 1,
    backgroundColor: '#020617',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoCircle: {
    width: 100,
    height: 100,
    backgroundColor: '#7C3AED',
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    elevation: 20,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  logoText: {
    color: '#FFF',
    fontSize: 60,
    fontWeight: '900',
    fontStyle: 'normal',
  },
  appName: {
    color: '#FFF',
    fontSize: 34,
    fontWeight: 'bold',
    letterSpacing: 4,
    textShadowColor: 'rgba(124, 58, 237, 0.5)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 10,
  },

  // Main UI Styles
  container: {
    flex: 1,
    backgroundColor: '#020617',
    paddingTop: 20,
    overflow: 'hidden',
  },
  bgBlob1: {
    position: 'absolute',
    top: -150,
    right: -100,
    width: 500,
    height: 500,
    borderRadius: 250,
    backgroundColor: 'rgba(76, 29, 149, 0.2)',
  },
  bgBlob2: {
    position: 'absolute',
    bottom: -200,
    left: -100,
    width: 600,
    height: 600,
    borderRadius: 300,
    backgroundColor: 'rgba(30, 27, 75, 0.4)',
  },
  bgBlob3: {
    position: 'absolute',
    top: '30%',
    left: -150,
    width: 400,
    height: 400,
    borderRadius: 200,
    backgroundColor: 'rgba(112, 26, 117, 0.12)',
  },
  scrollArea: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  headerLogo: {
    width: 42,
    height: 42,
    backgroundColor: '#7C3AED',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  headerLogoText: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '900',
    fontStyle: 'italic',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  greeting: {
    color: '#FFF',
    fontSize: 22,
    fontWeight: 'bold',
  },
  subGreeting: {
    color: '#9CA3AF',
    fontSize: 14,
    marginTop: 4,
  },
  headerIcons: {
    flexDirection: 'row',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#1C1C24',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
    borderWidth: 1,
    borderColor: '#2D2D3A',
  },
  walletCard: {
    backgroundColor: '#5B21B6',
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
  },
  walletLabel: {
    color: '#D8B4FE',
    fontSize: 14,
    marginBottom: 8,
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  balanceText: {
    color: '#FFF',
    fontSize: 32,
    fontWeight: 'bold',
    marginRight: 12,
  },
  percentBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  percentText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '600',
  },
  actionBtn: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '600',
  },
  sectionTitleInternal: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '600',
    marginTop: 24,
    marginBottom: 16,
  },
  seeAll: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  assetCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1C1C24',
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
  },
  assetLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  assetIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  assetName: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  assetSub: {
    color: '#9CA3AF',
    fontSize: 13,
  },
  overviewSummaryCard: {
    backgroundColor: '#1C1C24',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#2D2D3A',
  },
  overviewLabel: {
    color: '#9CA3AF',
    fontSize: 14,
    marginBottom: 6,
  },
  overviewAmount: {
    color: '#FFF',
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  overviewCompareText: {
    color: '#9CA3AF',
    fontSize: 13,
  },
  chartContainer: {
    backgroundColor: '#1C1C24',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2D2D3A',
  },
  barsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    width: '100%',
    height: 160,
    paddingTop: 10,
  },
  barWrapper: {
    alignItems: 'center',
    flex: 1,
  },
  bar: {
    width: 12,
    backgroundColor: 'rgba(139, 92, 246, 0.3)',
    borderRadius: 6,
    marginBottom: 8,
  },
  barLabel: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '500',
  },
  categoryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1C1C24',
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#2D2D3A',
  },
  categoryIconBg: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  categoryName: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '500',
  },
  categoryPrice: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  progressTrack: {
    height: 6,
    backgroundColor: '#2D2D3A',
    borderRadius: 3,
    width: '100%',
  },
  progressFill: {
    height: '100%',
    borderRadius: 3,
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(11, 14, 31, 0.96)',
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 10,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderTopWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
  },
  navText: {
    fontSize: 10,
    marginTop: 4,
  },
  centerNavBtnWrapper: {
    top: -20,
  },
  centerNavBtn: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#D946EF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#D946EF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 8,
  },
  toastContainer: {
    position: 'absolute',
    top: 50,
    left: 20,
    right: 20,
    backgroundColor: '#1C1C24',
    borderRadius: 16,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 5000,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  toastIconBg: {
    padding: 8,
    borderRadius: 10,
  },
  toastTitle: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  toastDesc: {
    color: '#9CA3AF',
    fontSize: 12,
    marginTop: 2,
  },
  // Promo Cards Styles
  promoContainer: {
    marginBottom: 24,
  },
  promoScroll: {
    paddingLeft: 20,
    paddingRight: 10,
  },
  promoCard: {
    width: 160,
    padding: 16,
    borderRadius: 24,
    marginRight: 12,
    borderWidth: 1,
  },
  promoIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  promoTitle: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  promoPrice: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
  },
});